/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class field_syphon_SyphonClient */

#ifndef _Included_field_syphon_SyphonClient
#define _Included_field_syphon_SyphonClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     field_syphon_SyphonClient
 * Method:    getServerDescriptions
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_field_syphon_SyphonClient_getServerDescriptions
  (JNIEnv *, jclass);

/*
 * Class:     field_syphon_SyphonClient
 * Method:    initWithUUID
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_field_syphon_SyphonClient_initWithUUID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     field_syphon_SyphonClient
 * Method:    hasNewFrame
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_field_syphon_SyphonClient_hasNewFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     field_syphon_SyphonClient
 * Method:    isValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_field_syphon_SyphonClient_isValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     field_syphon_SyphonClient
 * Method:    bindNow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_field_syphon_SyphonClient_bindNow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     field_syphon_SyphonClient
 * Method:    widthNow
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_field_syphon_SyphonClient_widthNow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     field_syphon_SyphonClient
 * Method:    heightNow
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_field_syphon_SyphonClient_heightNow
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
